# Generated by Django 3.2.6 on 2021-11-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Digite o nome da carta', max_length=100)),
                ('poder', models.IntegerField(help_text='Digite o poder de ataque da carta', verbose_name='Poder de ataque')),
                ('raca', models.CharField(help_text='Digite a raça da carta', max_length=100, verbose_name='Raça')),
                ('efeito', models.CharField(help_text='Digite o efeito da carta', max_length=100)),
                ('tipo', models.CharField(help_text='Digite o tipo da carta', max_length=100)),
                ('classe', models.CharField(help_text='Digite a classe da carta', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(help_text='Digite o nome de usuário', max_length=100)),
                ('password', models.CharField(help_text='Digite a sua senha', max_length=100)),
                ('email', models.EmailField(help_text='Entre com o seu email', max_length=200)),
            ],
        ),
    ]
