# Generated by Django 3.2.6 on 2021-11-28 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardMakerApp', '0005_auto_20211127_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='classe',
            field=models.CharField(choices=[('Necromancer', 'Necromancer'), ('Forest Folk', 'Forest Folk'), ('Fighter', 'Fighter'), ('Mage', 'Mage'), ('Royal Kingdom', 'Royal Kingdom'), ('Neutral', 'Neutral')], help_text='Escolha a classe', max_length=100),
        ),
        migrations.AlterField(
            model_name='carta',
            name='tipo',
            field=models.CharField(choices=[('Equipment', 'Equipment'), ('Spell', 'Spell'), ('Fighter', 'Fighter')], help_text='Escolha o tipo', max_length=100),
        ),
    ]
