# Generated by Django 3.2.6 on 2021-11-28 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardMakerApp', '0006_auto_20211127_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='carta',
            name='usuario',
            field=models.CharField(default='username', help_text='Usuário', max_length=100),
            preserve_default=False,
        ),
    ]
