# Generated by Django 3.2.6 on 2021-11-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CardMakerApp', '0003_alter_carta_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='classe',
            field=models.CharField(choices=[('necromancer', 'Necromancer'), ('forestFolk', 'Forest Folk'), ('fighter', 'Fighter'), ('mage', 'Mage'), ('royalKingdom', 'Royal Kingdom'), ('neutral', 'Neutral')], help_text='Digite a classe da carta', max_length=100),
        ),
    ]
